# Generated by Django 4.2.1 on 2024-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcity', '0003_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
