# Generated by Django 4.2.1 on 2024-11-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcity', '0004_alter_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='time_creat',
            new_name='time_create',
        ),
    ]
