# Generated by Django 4.2.1 on 2024-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcity', '0006_alter_city_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
